id: IFF503EF1
legacy_id: P008241
ocr_import_info:
  bdrc_scan_id: W29197
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T02:04:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:11:29.648877+00:00'
last_modified: 2022-09-02 18:12:12.509741
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29197
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29197
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པའི་བཤད་སྦྱར་རྩོད་མེད་ཆེ་བའི་འབྱུང་གནས།
  author: སློབ་དཔོན་ཐེག་མཆོག
statistics:
  ocr_word_mean_confidence_index: 0.8565966909517152
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I5162:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5162
      total_pages: 736
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5162.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8565966909517152
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
