id: IFF503EF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:09:07+00:00'
last_modified: '2022-06-08T08:10:33.237113+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29197
  title: དབུ་མ་ལ་འཇུག་པའི་བཤད་སྦྱར་རྩོད་མེད་ཆེ་བའི་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F6BB:
      image_group_id: I5162
      title: ''
      total_pages: 736
      order: 1
      base_file: F6BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
