id: P008241
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:10:05.593122
source_metadata:
  id: bdr:W29197
  title: དབུ་མ་ལ་འཇུག་པའི་བཤད་སྦྱར་རྩོད་མེད་ཆེ་བའི་འབྱུང་གནས
  author: ''
  volumes:
    2120c532f0654b4eb3051f34879c90cc:
      image_group_id: I5162
      title: ''
      volume_number: 1
      total_pages: 736
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
